apiVersion: apps/v1
kind: Deployment
metadata:
  name: roar-web
  labels:
    name: roar-web
    app: roar-web
  namespace: roar
spec:
  selector:
    matchLabels:
      app: roar-web  
  replicas: 1
  template:
    metadata:
      labels:
        name: roar-web
        app: roar-web
    spec:
      containers:
      - name: roar-web
        image: quay.io/bclaster/roar-web:1.0.1
        ports:
        - name: web
          containerPort: 8080
