apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: roar-db
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roar-db
  template:
    metadata:
      labels:
        app: roar-db
        name: mysql
    spec:
      containers:
      - name: mysql
        image: quay.io/techupskills/roar-db:v2
        env:
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: mysql-configmap
                key: mysql.database
          - name: MYSQL_PASSWORD
            valueFrom: 
              secretKeyRef:
                name: mysqlsecret
                key: mysqlpassword
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysqlsecret
                key: mysqlrootpassword
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                name: mysql-configmap
                key: mysql.user
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
          name: mysql
