apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: prepull
spec:
  selector:
    matchLabels:
      name: prepull 
  template:
    metadata:
      labels:
        name: prepull 
    spec:
      initContainers:
      - name: prepull 
        image: docker
        command: ["/bin/sh", "-c"]
        args:
          -  docker pull quay.io/bclaster/roar-db-test:v4;
             docker pull quay.io/bclaster/roar-web:1.0.1;
             docker pull quay.io/bclaster/roar-web:v2;
             docker pull quay.io/techupskills/roar-db:v2;
             docker pull quay.io/techupskills/roar-web:v1;
             docker pull quay.io/techupskills2/roarapp-operator:2.0.0;
        volumeMounts:
        - name: docker
          mountPath: /var/run
      volumes:
      - name: docker
        hostPath:
          path: /var/run
      containers:
      - name: pause
        image: gcr.io/google_containers/pause
