apiVersion: apps/v1
kind: Deployment
metadata:
  name: roarapp-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: roarapp-operator
  template:
    metadata:
      labels:
        name: roarapp-operator
    spec:
      serviceAccountName: roarapp-operator
      containers:
        - name: roarapp-operator
          # Replace this with the built image name
          image: quay.io/bclaster/roarapp-operator:v2
          command:
          - roarapp-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "roarapp-operator"
