apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: roarapps.app.example.com
spec:
  group: app.example.com
  names:
    kind: RoarApp
    listKind: RoarAppList
    plural: roarapps
    singular: roarapp
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                apiVersion:
                  type: string
                kind:
                  type: string
                metadata:
                  type: object
                replicas:
                  format: int32
                  type: integer
                podNames:
                  items:
                    type: string
                  type: array
              
